---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureClusterIdentity
metadata:
  name: "${CLUSTER_IDENTITY_NAME}"
  labels:
    clusterctl.cluster.x-k8s.io/move-hierarchy: "true"
spec:
  type: "${CLUSTER_IDENTITY_TYPE:=WorkloadIdentity}"
  allowedNamespaces: {}
  tenantID: "${AZURE_TENANT_ID}"
  clientID: "${AZURE_CLIENT_ID_USER_ASSIGNED_IDENTITY}"
