apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
- ../default
- machine-deployment-windows.yaml

patches:
- path: ../base-windows-containerd/cluster.yaml

sortOptions:
  order: fifo
