apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
- ../default
patches:
- path: patches/azure-extendedlocation.yaml
- path: patches/azure-remove-natgateway.yaml

sortOptions:
  order: fifo
