apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
- clusterclass.yaml
- azure-cluster-template.yaml
- azure-machine-template-controlplane.yaml
- azure-machine-template-worker.yaml
- kubeadm-controlplane-template.yaml
- kubeadm-config-template.yaml
- ../../azure-cluster-identity

sortOptions:
  order: fifo
